#!/bin/sh

i=0
for args in \
"--flag=conv        --batch_size=16   --fuse=2    --test_iter=100" \
"--flag=conv        --batch_size=16   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=1    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=1    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=3    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=3    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=4    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=4    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=5    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=5    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=6    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=6    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=7    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=7    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=8    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=8    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=9    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=9    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=10    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=10    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=11    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=11    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=12    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=12    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=13    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=13    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=14    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=14    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=15    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=15    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=16    --test_iter=100" \
"--flag=batchedconv --batch_size=16   --fuse=16    --test_iter=100" \
"--flag=conv        --batch_size=32   --fuse=2    --test_iter=100" \
"--flag=conv        --batch_size=32   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=1    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=1    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=3    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=3    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=4    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=4    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=5    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=5    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=6    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=6    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=7    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=7    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=8    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=8    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=9    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=9    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=10    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=10    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=11    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=11    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=12    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=12    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=13    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=13    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=14    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=14    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=15    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=15    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=16    --test_iter=100" \
"--flag=batchedconv --batch_size=32   --fuse=16    --test_iter=100" \
"--flag=conv        --batch_size=64   --fuse=1    --test_iter=100" \
"--flag=conv        --batch_size=64   --fuse=1    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=1    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=1    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=2    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=3    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=3    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=4    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=4    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=5    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=5    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=6    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=6    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=7    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=7    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=8    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=8    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=9    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=9    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=10    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=10    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=11    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=11    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=12    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=12    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=13    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=13    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=14    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=14    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=15    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=15    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=16    --test_iter=100" \
"--flag=batchedconv --batch_size=64   --fuse=16    --test_iter=100" \
"--flag=conv        --batch_size=16   --fuse=2    --test_iter=1000" \
"--flag=conv        --batch_size=16   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=1    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=1    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=3    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=3    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=4    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=4    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=5    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=5    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=6    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=6    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=7    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=7    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=8    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=8    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=9    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=9    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=10    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=10    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=11    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=11    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=12    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=12    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=13    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=13    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=14    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=14    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=15    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=15    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=16    --test_iter=1000" \
"--flag=batchedconv --batch_size=16   --fuse=16    --test_iter=1000" \
"--flag=conv        --batch_size=32   --fuse=2    --test_iter=1000" \
"--flag=conv        --batch_size=32   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=1    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=1    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=3    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=3    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=4    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=4    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=5    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=5    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=6    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=6    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=7    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=7    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=8    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=8    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=9    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=9    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=10    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=10    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=11    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=11    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=12    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=12    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=13    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=13    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=14    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=14    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=15    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=15    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=16    --test_iter=1000" \
"--flag=batchedconv --batch_size=32   --fuse=16    --test_iter=1000" \
"--flag=conv        --batch_size=64   --fuse=1    --test_iter=1000" \
"--flag=conv        --batch_size=64   --fuse=1    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=1    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=1    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=2    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=3    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=3    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=4    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=4    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=5    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=5    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=6    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=6    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=7    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=7    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=8    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=8    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=9    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=9    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=10    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=10    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=11    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=11    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=12    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=12    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=13    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=13    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=14    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=14    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=15    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=15    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=16    --test_iter=1000" \
"--flag=batchedconv --batch_size=64   --fuse=16    --test_iter=1000" \

do
  echo "==============================" >> testlogs3.txt
  echo "Running task $i:  $args" >> testlogs3.txt
  echo "==============================" >> testlogs3.txt

  python script_fuseParallel/HorizontalFusionTest.py $args >> testlogs3.txt 2>&1
  echo "" >> testlogs3.txt

  i=$((i + 1))
done
